import {
  Loading,
  Pagination,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  MessageBox,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Notification,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Message,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Transfer,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Timeline,
  TimelineItem,
  Link,
  Divider,
  Image,
  Calendar,
  Backtop,
  InfiniteScroll,
  PageHeader,
  Avatar,
  Drawer,
  Popconfirm,
  Scrollbar
} from 'element-ui'
// import Scrollbar from 'element-ui'
// 接口类型
export interface OrderItem {
  name: string
  entry: string | { scripts?: string[]; styles?: string[]; html?: string }
  container: string | HTMLElement
  activeRule: string | ((location: Location) => boolean) | Array<string | ((location: Location) => boolean)>
  props: object
}

export const list: OrderItem[] = [
  {
    name: 'ggnavmenu',
    entry: '//localhost:8081',
    activeRule: () => true,
    container: '#subapp-viewport',
    props: { Scrollbar, Menu, Submenu, MenuItem, MenuItemGroup }
  }
]
